<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#070b17">
    <meta name="robots" content="noindex,nofollow">
    <meta name="description" content="Oferta Vitrine Social Mídia: planos mensais e condição VIP anual para organizar e fortalecer a presença digital da sua empresa.">
    <title>Oferta VIP | Vitrine Social Mídia</title>
    <style>
        :root{--bg:#070b17;--surface:#0d1324;--surface-2:#111a31;--line:rgba(255,255,255,.09);--text:#f7f9ff;--muted:#a8b3cf;--cyan:#25d9ff;--blue:#4b7cff;--violet:#8b5cf6;--magenta:#ff4fd8;--gold:#ffc928;--green:#79f2b0;--radius:24px;--shadow:0 24px 80px rgba(0,0,0,.38)}
        *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:radial-gradient(circle at 12% 8%,rgba(37,217,255,.14),transparent 28%),radial-gradient(circle at 88% 12%,rgba(255,79,216,.12),transparent 24%),linear-gradient(180deg,#070b17 0%,#090f1e 46%,#070b17 100%);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;line-height:1.5}
        a{color:inherit;text-decoration:none}.wrap{width:min(1160px,calc(100% - 40px));margin:auto}.nav{position:sticky;top:0;z-index:20;background:rgba(7,11,23,.78);backdrop-filter:blur(18px);border-bottom:1px solid var(--line)}.nav-inner{height:76px;display:flex;align-items:center;justify-content:space-between;gap:24px}.brand{font-weight:900;letter-spacing:-.04em;font-size:1.18rem}.brand span{background:linear-gradient(90deg,var(--cyan),var(--violet),var(--magenta));-webkit-background-clip:text;color:transparent}.nav-links{display:flex;gap:22px;color:var(--muted);font-size:.92rem}.btn{display:inline-flex;align-items:center;justify-content:center;min-height:46px;padding:0 18px;border-radius:14px;border:1px solid var(--line);font-weight:800;transition:.2s ease}.btn:hover{transform:translateY(-1px);border-color:rgba(37,217,255,.42)}.btn-primary{border:0;background:linear-gradient(135deg,var(--cyan),var(--blue) 45%,var(--violet));box-shadow:0 14px 36px rgba(75,124,255,.26);color:white}.btn-gold{border:0;background:linear-gradient(135deg,#ffdf5a,var(--gold));color:#171102;box-shadow:0 14px 38px rgba(255,201,40,.2)}
        .hero{padding:94px 0 66px}.hero-grid{display:grid;grid-template-columns:1.06fr .94fr;gap:48px;align-items:center}.eyebrow{display:inline-flex;gap:8px;align-items:center;padding:8px 12px;border-radius:999px;background:rgba(37,217,255,.08);border:1px solid rgba(37,217,255,.22);color:#b7f4ff;font-weight:800;font-size:.78rem;letter-spacing:.08em;text-transform:uppercase}h1{font-size:clamp(3rem,6vw,5.35rem);line-height:.95;letter-spacing:-.065em;margin:22px 0}.gradient{background:linear-gradient(92deg,var(--cyan),#8cb0ff 40%,var(--violet) 70%,var(--magenta));-webkit-background-clip:text;color:transparent}.lead{font-size:1.16rem;color:var(--muted);max-width:650px}.hero-actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:30px}.trust{display:flex;gap:20px;flex-wrap:wrap;margin-top:26px;color:#c4cce0;font-size:.9rem}.trust b{color:white}
        .offer-box{padding:26px;border-radius:30px;background:linear-gradient(155deg,rgba(18,28,53,.97),rgba(8,13,27,.97));border:1px solid rgba(255,255,255,.11);box-shadow:var(--shadow);position:relative;overflow:hidden}.offer-box:before{content:"";position:absolute;width:260px;height:260px;border-radius:50%;background:rgba(255,201,40,.08);right:-90px;top:-120px;filter:blur(4px)}.offer-box h2{margin:12px 0 6px;font-size:1.8rem;letter-spacing:-.04em}.offer-box p{color:var(--muted);margin:0 0 18px}.offer-kpi{display:grid;grid-template-columns:1fr 1fr;gap:10px}.kpi{padding:16px;border-radius:18px;background:#0b1224;border:1px solid var(--line)}.kpi small{display:block;color:var(--muted)}.kpi strong{display:block;font-size:1.15rem;margin-top:5px}.kpi.gold strong{color:#ffe075}.kpi.green strong{color:var(--green)}
        .section{padding:82px 0}.section-head{max-width:790px;margin-bottom:34px}.section-head h2{font-size:clamp(2rem,4vw,3.5rem);letter-spacing:-.05em;line-height:1.02;margin:12px 0}.section-head p{color:var(--muted);font-size:1.05rem}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.card{padding:26px;border-radius:var(--radius);background:linear-gradient(180deg,rgba(17,26,49,.86),rgba(11,18,36,.88));border:1px solid var(--line)}.card h3{margin:0 0 8px}.card p{margin:0;color:var(--muted)}
        .plans{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;align-items:stretch}.plan{position:relative;padding:28px;border-radius:28px;background:linear-gradient(180deg,rgba(17,26,49,.95),rgba(9,15,30,.96));border:1px solid var(--line);display:flex;flex-direction:column;min-height:100%}.plan.featured{border-color:rgba(255,201,40,.48);box-shadow:0 20px 70px rgba(255,201,40,.12)}.badge{position:absolute;top:18px;right:18px;padding:7px 10px;border-radius:999px;background:rgba(255,201,40,.12);border:1px solid rgba(255,201,40,.28);color:#ffe277;font-size:.72rem;font-weight:900;text-transform:uppercase;letter-spacing:.08em}.plan-name{font-size:1.3rem;font-weight:900}.monthly{color:var(--muted);margin-top:8px}.price{font-size:2.55rem;font-weight:950;letter-spacing:-.055em;margin:16px 0 2px}.price span{font-size:.9rem;font-weight:700;color:var(--muted);letter-spacing:0}.saving{color:var(--green);font-size:.88rem;font-weight:800;margin-bottom:18px}.plan ul{list-style:none;padding:0;margin:16px 0 24px;display:grid;gap:10px;color:#d4daf0}.plan li:before{content:"✓";color:var(--cyan);font-weight:900;margin-right:8px}.plan .btn{margin-top:auto;width:100%}.note{margin-top:18px;color:var(--muted);font-size:.86rem;text-align:center}
        .compare{overflow-x:auto;border:1px solid var(--line);border-radius:24px}.compare table{width:100%;border-collapse:collapse;min-width:760px;background:rgba(9,15,30,.72)}.compare th,.compare td{padding:16px 18px;border-bottom:1px solid var(--line);text-align:left}.compare th{color:white;background:rgba(255,255,255,.025)}.compare td{color:#d1d8eb}.compare tr:last-child td{border-bottom:0}.yes{color:var(--green);font-weight:900}
        .bonus{padding:34px;border-radius:30px;background:linear-gradient(135deg,rgba(37,217,255,.12),rgba(139,92,246,.16) 55%,rgba(255,79,216,.11));border:1px solid rgba(139,92,246,.25)}.bonus-grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:14px;margin-top:24px}.bonus-item{padding:20px;border-radius:20px;background:rgba(7,11,23,.5);border:1px solid var(--line)}.bonus-item strong{display:block;margin-bottom:6px}.bonus-item span{color:var(--muted);font-size:.92rem}
        .flow{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.step{padding:22px;border-radius:20px;background:#0b1224;border:1px solid var(--line)}.step em{font-style:normal;font-size:.75rem;color:var(--cyan);font-weight:900}.step h3{margin:10px 0 8px}.step p{color:var(--muted);margin:0;font-size:.9rem}.faq{display:grid;gap:12px}.faq details{padding:18px 20px;border-radius:18px;background:#0b1224;border:1px solid var(--line)}.faq summary{cursor:pointer;font-weight:850}.faq p{color:var(--muted);margin:12px 0 0}.cta{padding:40px;border-radius:32px;background:linear-gradient(135deg,rgba(255,201,40,.12),rgba(37,217,255,.12),rgba(139,92,246,.15));border:1px solid rgba(255,255,255,.12);text-align:center}.cta h2{font-size:clamp(2rem,4vw,3.4rem);letter-spacing:-.05em;margin:0 0 10px}.cta p{color:var(--muted);max-width:720px;margin:0 auto 24px}.footer{padding:34px 0 46px;border-top:1px solid var(--line);color:var(--muted);font-size:.88rem}.footer-inner{display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap}.footer strong{color:white}
        @media(max-width:900px){.nav-links{display:none}.hero-grid{grid-template-columns:1fr}.plans,.cards{grid-template-columns:1fr}.bonus-grid{grid-template-columns:1fr}.flow{grid-template-columns:1fr 1fr}.offer-box{max-width:680px}}
        @media(max-width:620px){.wrap{width:min(100% - 26px,1160px)}.nav-inner{height:68px}.hero{padding:54px 0 48px}h1{font-size:clamp(2.7rem,15vw,4.2rem)}.offer-kpi,.flow{grid-template-columns:1fr}.section{padding:62px 0}.hero-actions .btn,.cta .btn{width:100%}}
    </style>
</head>
<body>
<header class="nav">
    <div class="wrap nav-inner">
        <a class="brand" href="/">Vitrine <span>Social Mídia</span></a>
        <nav class="nav-links" aria-label="Navegação da oferta"><a href="#beneficios">Benefícios</a><a href="#planos">Planos</a><a href="#vip">VIP</a><a href="#faq">Dúvidas</a></nav>
        <a class="btn btn-gold" href="#planos">Ver oferta VIP</a>
    </div>
</header>
<main>
<section class="hero">
    <div class="wrap hero-grid">
        <div>
            <span class="eyebrow">Condição VIP de lançamento</span>
            <h1>Sua empresa <span class="gradient">visível, relevante e lembrada.</span></h1>
            <p class="lead">Transforme sua presença digital em uma operação organizada: planejamento, criação, aprovação, calendário, publicação e acompanhamento em um só lugar.</p>
            <div class="hero-actions"><a class="btn btn-gold" href="#planos">Quero a condição VIP</a><a class="btn" href="#como-funciona">Como funciona</a></div>
            <div class="trust"><span><b>12 meses</b> pelo equivalente a 10</span><span><b>Onboarding</b> prioritário</span><span><b>Planejamento</b> inicial incluído</span></div>
        </div>
        <aside class="offer-box">
            <span class="eyebrow">Por que entrar agora</span>
            <h2>Mais previsibilidade. Menos improviso.</h2>
            <p>A Vitrine Social Mídia centraliza sua rotina de conteúdo e dá clareza para acompanhar o que está sendo produzido, aprovado e publicado.</p>
            <div class="offer-kpi"><div class="kpi gold"><small>Condição anual</small><strong>2 mensalidades de economia</strong></div><div class="kpi green"><small>Entrada VIP</small><strong>Bônus de implantação</strong></div><div class="kpi"><small>Operação</small><strong>Calendário + aprovação</strong></div><div class="kpi"><small>Suporte</small><strong>VIA integrada</strong></div></div>
        </aside>
    </div>
</section>
<section class="section" id="beneficios">
    <div class="wrap">
        <div class="section-head"><span class="eyebrow">O que muda na prática</span><h2>Uma rotina de conteúdo estruturada para sua empresa não desaparecer das redes.</h2><p>Você deixa de depender de ideias soltas e passa a trabalhar com planejamento, cadência e acompanhamento.</p></div>
        <div class="cards"><article class="card"><h3>Planejamento editorial</h3><p>Conteúdos organizados por objetivo, período e prioridade.</p></article><article class="card"><h3>Criação com IA + revisão</h3><p>Produção acelerada com apoio de IA e fluxo operacional de revisão.</p></article><article class="card"><h3>Aprovação centralizada</h3><p>Revise, aprove ou solicite ajustes sem perder histórico e contexto.</p></article><article class="card"><h3>Calendário e publicação</h3><p>Saiba o que será publicado e quando, conforme as condições do seu plano.</p></article><article class="card"><h3>Vídeos e avatar</h3><p>Recursos de vídeo e avatar disponíveis conforme o plano ou por pacotes adicionais.</p></article><article class="card"><h3>Visão de desempenho</h3><p>Acompanhe os principais sinais da presença digital dentro do painel.</p></article></div>
    </div>
</section>
<section class="section" id="planos">
    <div class="wrap">
        <div class="section-head"><span class="eyebrow">Planos</span><h2>Escolha seu nível de operação. No VIP anual, você paga o equivalente a 10 meses e usa 12.</h2><p>Os preços mensais continuam disponíveis como referência. A condição anual abaixo é exclusiva da oferta VIP de lançamento.</p></div>
        <div class="plans">
            <article class="plan"><div class="plan-name">Essencial</div><div class="monthly">Mensal: R$ 79,90</div><div class="price">R$ 799<span>/ano</span></div><div class="saving">Economia de R$ 159,80</div><ul><li>100 créditos por mês</li><li>Até 10 conteúdos padrão</li><li>1 perfil/marca</li><li>Posts, carrosséis e Stories</li><li>Legenda, CTA e hashtags</li><li>Roteiros de vídeo</li></ul><a class="btn btn-primary" href="mailto:vitrineiapro@gmail.com?subject=Quero%20o%20Essencial%20Anual%20VIP&body=Tenho%20interesse%20no%20plano%20Essencial%20Anual%20VIP%20da%20Vitrine%20Social%20M%C3%ADdia.">Escolher Essencial VIP</a></article>
            <article class="plan featured"><span class="badge">Mais indicado</span><div class="plan-name">Pro</div><div class="monthly">Mensal: R$ 169,90</div><div class="price">R$ 1.699<span>/ano</span></div><div class="saving">Economia de R$ 339,80</div><ul><li>250 créditos por mês</li><li>Até 25 conteúdos</li><li>Calendário editorial</li><li>Agendamento incluído</li><li>Publicação em redes homologadas</li><li>Condições diferenciadas para vídeo</li><li>Suporte prioritário</li></ul><a class="btn btn-gold" href="mailto:vitrineiapro@gmail.com?subject=Quero%20o%20Pro%20Anual%20VIP&body=Tenho%20interesse%20no%20plano%20Pro%20Anual%20VIP%20da%20Vitrine%20Social%20M%C3%ADdia.">Escolher Pro VIP</a></article>
            <article class="plan"><div class="plan-name">Premium</div><div class="monthly">Mensal: R$ 349,90</div><div class="price">R$ 3.499<span>/ano</span></div><div class="saving">Economia de R$ 699,80</div><ul><li>500 créditos por mês</li><li>Até 50 conteúdos</li><li>Agendamento e publicação</li><li>300s de vídeo renderizado/mês</li><li>60s de avatar incluídos</li><li>Revisão editorial ampliada</li></ul><a class="btn btn-primary" href="mailto:vitrineiapro@gmail.com?subject=Quero%20o%20Premium%20Anual%20VIP&body=Tenho%20interesse%20no%20plano%20Premium%20Anual%20VIP%20da%20Vitrine%20Social%20M%C3%ADdia.">Escolher Premium VIP</a></article>
        </div>
        <p class="note">Regra de conteúdo: 10 créditos = 1 conteúdo padrão. Recursos e integrações dependem das redes homologadas e do escopo de cada plano.</p>
    </div>
</section>
<section class="section" id="vip">
    <div class="wrap bonus"><span class="eyebrow">Bônus VIP</span><div class="section-head" style="margin-bottom:0"><h2>Quem entra no anual começa com uma implantação mais assistida.</h2><p>Além da economia anual, a condição VIP inclui benefícios de entrada para acelerar o primeiro ciclo.</p></div><div class="bonus-grid"><div class="bonus-item"><strong>Onboarding prioritário</strong><span>Organização inicial da conta e orientação para iniciar a operação.</span></div><div class="bonus-item"><strong>Diagnóstico inicial</strong><span>Leitura da presença digital atual para orientar os primeiros movimentos.</span></div><div class="bonus-item"><strong>Planejamento do primeiro ciclo</strong><span>Estrutura inicial de conteúdo e prioridades para começar com direção.</span></div></div></div>
</section>
<section class="section" id="como-funciona">
    <div class="wrap"><div class="section-head"><span class="eyebrow">Como funciona</span><h2>Da entrada à publicação em quatro etapas.</h2></div><div class="flow"><article class="step"><em>01</em><h3>Onboarding</h3><p>Recebemos os dados da empresa, marca, objetivos e canais.</p></article><article class="step"><em>02</em><h3>Planejamento</h3><p>Definimos o primeiro ciclo de conteúdo e a cadência.</p></article><article class="step"><em>03</em><h3>Criação e aprovação</h3><p>Os conteúdos entram no fluxo para sua revisão e aprovação.</p></article><article class="step"><em>04</em><h3>Publicação e acompanhamento</h3><p>O calendário e os resultados ficam centralizados na experiência.</p></article></div></div>
</section>
<section class="section"><div class="wrap"><div class="section-head"><span class="eyebrow">Comparativo rápido</span><h2>Mensal para flexibilidade. Anual VIP para melhor condição.</h2></div><div class="compare"><table><thead><tr><th>Condição</th><th>Mensal</th><th>Anual VIP</th></tr></thead><tbody><tr><td>Compromisso</td><td>Mês a mês</td><td>12 meses</td></tr><tr><td>Preço de referência</td><td>12 mensalidades</td><td>Equivalente a 10 mensalidades</td></tr><tr><td>Economia</td><td>—</td><td class="yes">2 mensalidades</td></tr><tr><td>Onboarding prioritário</td><td>Padrão</td><td class="yes">Incluído</td></tr><tr><td>Diagnóstico inicial</td><td>Padrão</td><td class="yes">Incluído</td></tr><tr><td>Planejamento do primeiro ciclo</td><td>Padrão</td><td class="yes">Incluído</td></tr></tbody></table></div></div></section>
<section class="section" id="faq"><div class="wrap"><div class="section-head"><span class="eyebrow">Dúvidas frequentes</span><h2>Antes de escolher seu plano.</h2></div><div class="faq"><details><summary>O que significa 10 créditos = 1 conteúdo padrão?</summary><p>É a unidade operacional usada para controlar a franquia de conteúdos. Cada 10 créditos correspondem a um conteúdo padrão dentro do escopo previsto.</p></details><details><summary>Vídeo está incluído em todos os planos?</summary><p>O Premium inclui 300 segundos de vídeo renderizado por mês. Nos demais planos, vídeo é tratado por condições específicas ou pacotes adicionais.</p></details><details><summary>O Premium inclui avatar?</summary><p>Sim. O Premium prevê 60 segundos de avatar incluídos por mês. Consumos adicionais podem ser contratados separadamente.</p></details><details><summary>Posso contratar mensalmente?</summary><p>Sim. Os preços mensais continuam como referência comercial. A condição VIP anual foi criada para quem prefere compromisso anual em troca de economia e benefícios de implantação.</p></details><details><summary>As publicações são automáticas em qualquer rede?</summary><p>Publicação e integrações dependem das redes e fluxos homologados pela operação. O escopo deve ser confirmado no momento da contratação.</p></details></div></div></section>
<section class="section"><div class="wrap cta"><span class="eyebrow">Condição VIP</span><h2>Escolha o plano anual e comece com vantagem.</h2><p>Economize duas mensalidades e entre com onboarding prioritário, diagnóstico inicial e planejamento do primeiro ciclo.</p><a class="btn btn-gold" href="#planos">Ver planos anuais VIP</a></div></section>
</main>
<footer class="footer"><div class="wrap footer-inner"><div><strong>Vitrine Social Mídia</strong> · Vitrine IA Pro</div><div>Oferta comercial sujeita à formalização da contratação e às condições aplicáveis ao plano escolhido.</div></div></footer>
</body>
</html>
